config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :categories, :questions
  get 'welcome/data_binding' => 'welcome#data_binding'
  get 'welcome/module_practice' => 'welcome#module_practice'
  get 'welcome/exercise_1' => 'welcome#exercise_1'
  get 'welcome/exercise_2' => 'welcome#exercise_2'
  get 'welcome/exercise_3' => 'welcome#exercise_3'
  get 'welcome/exercise_4' => 'welcome#exercise_4'
  get 'welcome/services_intro' => 'welcome#services_intro'
  get 'welcome/solution_1' => 'welcome#solution_1'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :questions
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :category
  has_many :replies
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :question
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories}
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions}
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def exercise_1
  end

  def exercise_2
  end

  def exercise_3
  end

  def exercise_4
  end

  def data_binding
  end

  def module_practice
  end

  def services_intro
  end

  def solution_1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<div class="jumbotron" ng-app="category">
  <header>
    <h1>Post Overflow: Learning Angular</h1>
  </header>
  <section ng-controller='CategoryController'>
    Display the list of Categories
    <ul>
      <li ng-repeat="cat in categoryData.cats">{{cat.name}}</li>
    </ul>
  </section>
</div>

app/views/categories/new.html.erb
<form>
  <div class="form-group row">
    <div class="col-xs-6">

      <label for="name">Category Name</label>
      <input type="text" class="form-control" id="name">
    </div>
  </div>
  <button type="submit" class="btn btn-default">Create</button>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PostOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<script type="text/javascript" src="/assets/js/angular-1.25.js"></script>
<script type="text/javascript" src="/assets/js/angular-route-1.25.js"></script>
<script type="text/javascript" src="/assets/js/main.js"></script>
<script type="text/javascript" src="/assets/js/student.js"></script>
<script type="text/javascript" src="/assets/js/my_first_service.js"></script>
<script type="text/javascript" src="/assets/js/using_services.js"></script>
<script type="text/javascript" src="/assets/js/category.js"></script>
<script type="text/javascript" src="/assets/js/category_service.js"></script>
<script type="text/javascript" src="/assets/js/question.js"></script>
<script type="text/javascript" src="/assets/js/question_services.js"></script>
</body>
</html>

app/views/questions/index.html.erb
<div class="jumbotron" ng-app="question">
  <header>
    <h1>Post Overflow: Learning how to use services</h1>
  </header>

  <section ng-controller="QuestionController">
    Display the list of questions
    <ul>
      <li ng-repeat="question in questionData.questions">{{question.description}}</li>
      <!-- ng-repeat iteration -->
    </ul>
  </section>
</div>

app/views/welcome/data_binding.html.erb
<div class="jumbotron" ng-app ng-init="first_number=1;second_number=1">
  <header>
    <h1>Two Way Data Binding</h1>
  </header>
  <h2>A basic calculator</h2>
  <div class="form-group row">
    <div class="col-xs-6">
      <label for="first_number">First Number</label>
      <input type="number" class="form-control" id="first_number" ng-model="first_number">
    </div>

    <div class="col-xs-6">
      <label for="second_number">Second Number</label>
      <input type="number" class="form-control" id="second_number" ng-model="second_number">
    </div>
  </div>

  <h3>Calculator Operations</h3>
  <p>Adding {{first_number}} with {{second_number}} results in {{first_number + second_number}}</p>
  <p>Subtracting {{first_number}} with {{second_number}} results in {{first_number - second_number}}</p>
  <p>Multiplying {{first_number}} with {{second_number}} results in {{first_number * second_number}}</p>
  <p>Dividing {{first_number}} with {{second_number}} results in {{first_number / second_number}}</p>
  <p>Modulo Operation of {{first_number}} with {{second_number}} results in {{first_number % second_number}}</p>
</div>

app/views/welcome/exercise_1.html.erb
<div class="jumbotron" ng-app ng-init="first_string,second_string">
  <header>
    <h1>Exercise1: You will be practising two way data binding here.</h1>
  </header>
  <div class="main-container">
    <div class="row">
      <h3>Problem: Create a Form that takes two strings and concatenates those two and outputs the result</h3>
    </div>

    <div class="form-group row">
      <div class="col-xs-6">
        <label for="first_string">First Name</label>
        <input type="text" class="form-control" id="first_string" ng-model="first_string" placeholder="First Name">
      </div>

      <div class="col-xs-6">
        <label for="second_string">Last Name</label>
        <input type="text" class="form-control" id="second_string" ng-model="second_string"  placeholder="Last Name">
      </div>
    </div>

    <h3>Name Parsed for {{first_string}}</h3>
    <p>
      For forms: {{second_string}}, {{first_string}}
    </p>
    <p>
      For reading: {{first_string}} {{second_string}}
    </p>
  </div>
</div>

app/views/welcome/exercise_2.html.erb
<div class="jumbotron" ng-app='hello'>
  <header>
    <h1>Exercise2: You will be practising creating modules and controllers</h1>
  </header>
  <div class="main-container" ng-controller="stringGameController">
    <div class="row">
      <h3>Convert the solution from Exercise 1 to a more modular code</h3>
      <ul>
        <li>create a file named student.js in the public/assets/js folder</li>
        <li>create a module named 'hello'</li>
        <li>add a controllers constructor function named 'StringGameController' to the module using the controller() method</li>
        <li>Write the relevant code in the StringGameController to perform the concatenation and adjust the view accordingly</li>
        <li>include the student.js file in exercise_2.html.erb</li>
      </ul>
    </div>
    <div class="form-group row">
      <div class="col-xs-6">
        <label for="firstName">First Name</label>
        <input type="text" class="form-control" id="firstName" ng-model="firstName" placeholder="First Name">
      </div>

      <div class="col-xs-6">
        <label for="lastName">Last Name</label>
        <input type="text" class="form-control" id="lastName" ng-model="lastName"  placeholder="Last Name">
      </div>
    </div>

    <h3>Name Parsed for {{firstName}}</h3>
    <p>
      For forms: {{lastName}}, {{firstName}}
    </p>
    <p>
      For reading: {{firstName}} {{lastName}}
    </p>
  </div>
  </div>
</div>

app/views/welcome/exercise_3.html.erb
<div class="jumbotron" ng-app="hello">
  <div class="main-container">
    <div class="row">
      <h3>In module_practice.html.erb update the code such that the Alternate calculator can be hidden and shown as well</h3>
    </div>
    <div class="main-container" ng-controller="stringGameController">
      <div class="row">
        <h3>Convert the solution from Exercise 1 to a more modular code</h3>
        <ul>
          <li>create a file named student.js in the public/assets/js folder</li>
          <li>create a module named 'hello'</li>
          <li>add a controllers constructor function named 'StringGameController' to the module using the controller() method</li>
          <li>Write the relevant code in the StringGameController to perform the concatenation and adjust the view accordingly</li>
          <li>include the student.js file in exercise_2.html.erb</li>
        </ul>
      </div>

      <h1>Give us your name</h1>
      <div ng-hide='firstHidden'>
        <div class="form-group row">
          <div class="col-xs-6">
            <label for="firstName">First Name</label>
            <input type="text" class="form-control" id="firstName" ng-model="firstName" placeholder="First Name">
          </div>

          <div class="col-xs-6">
            <label for="lastName">Last Name</label>
            <input type="text" class="form-control" id="lastName" ng-model="lastName"  placeholder="Last Name">
          </div>
        </div>

        <h3>Name Parsed for {{firstName}}</h3>
        <p>
          For forms: {{forms()}}
        </p>
        <p>
          For reading: {{reading()}}
        </p>
      </div>

      <button ng-click="hideFirst()" class="btn btn-success" name="button">{{firstButtonText}}</button>
    </div>

    <h1>What course do you want?</h1>
    <div class='main-container' ng-controller="stringGameControllerNew">
      <div ng-hide='secondHidden'>
        <div class="form-group row">
          <div class="col-xs-6">
            <label for="className">Class Name</label>
            <input type="text" class="form-control" id="className" ng-model="className" placeholder="Class Name">
          </div>

          <div class="col-xs-6">
            <label for="credits">Credits</label>
            <input type="number" class="form-control" id="credits" ng-model="credits"  placeholder="Number of Credits">
          </div>
        </div>

        <h3>{{classParse()}}</h3>
      </div>

      <button ng-click="hideSecond()" class="btn btn-success" name="button">{{secondButtonText}}</button>
    </div>
  </div>
</div>

app/views/welcome/exercise_4.html.erb
<div class="jumbotron">
  <header>
    <h1>Exercise4: You will be practising all you have learnt in Services and you will be using $http and $location service</h1>
  </header>
  <div class="main-container">
    <div class="row">
      <h3>In questions/index.html.erb Update the html code to list all the questions</h3><h3>You will have to send a json request to the server endpoint /questions.json</h3>
      <h3>Create a QuestionsService named by questions_service.js and place it in public/assets/js</h3>
      <h3>Create a question.js file and add the controllers constructor function</h3>
      <h3>Include the QuestionsService in the file where you code the QuestionsController</h3>
      <h3>You can look at the output of your code <%= link_to 'here', questions_path %></h2>
      <h3>  
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <header>
    <h1>Welcome To Angular Workshop</h1>
  </header>
 
  <h2><%= link_to 'Data Binding', welcome_data_binding_path %><h2>
  <h2><%= link_to 'Module Practice', welcome_module_practice_path %><h2>
  <h2><%= link_to 'Services Intro', welcome_services_intro_path %><h2>
  <h2><%= link_to 'Use HTTP and location service', categories_path %></h2>
  <h2><%= link_to 'Exercise 1', welcome_exercise_1_path %></h2>
  <h2><%= link_to 'Exercise 2', welcome_exercise_2_path %></h2>
  <h2><%= link_to 'Exercise 3', welcome_exercise_3_path %></h2>
  <h2><%= link_to 'Exercise 4', welcome_exercise_4_path %></h2>
  <h2><%= link_to 'Fork Me', 'https://github.com/sowjumn/post_overflow' %></h2>
  <h2><%= link_to 'Slides', 'http://www.slideshare.net/NagaSowjanyaMudunuri/angular-wwc-45777196' %></h2>
</div>

app/views/welcome/module_practice.html.erb
<div class="jumbotron" ng-app="workshop">
  <header>
    <h1>Modules, Controllers, Directives</h1>
  </header>
  <h2>A basic calculator</h2>
  <div class="main-container" ng-controller="CalculatorController">
    <div ng-hide="firstHidden">
      <div class="form-group row">
        <div class="col-xs-6">
          <label for="firstNumber">First Number</label>
          <input type="number" class="form-control" id="firstNumber" ng-model="firstNumber">
        </div>

        <div class="col-xs-6">
          <label for="secondNumber">Second Number</label>
          <input type="number" class="form-control" id="secondNumber" ng-model="secondNumber">
        </div>
      </div>

      <p>Adding {{firstNumber}} with {{secondNumber}} results in {{add()}}</p>
      <p>Subtracting {{firstNumber}} with {{secondNumber}} results in {{subtract()}}</p>
      <p>Multiplying {{firstNumber}} with {{secondNumber}} results in {{multiply()}}</p>
      <p>Dividing {{firstNumber}} with {{secondNumber}} results in {{divide()}}</p>
      <p>Modulo Operation of {{firstNumber}} with {{secondNumber}} results in {{modulo()}}</p>
    </div>
    <button ng-click="hideFirst()" class="btn btn-success">{{firstButtonText}}</button>
  </div>

  <h2>Alternate Calculator</h2>
  <div class="main-container" ng-controller="AlternateCalculateController as calc">
    <div ng-hide="secondHidden">
      <div class="form-group row">
        <div class="col-xs-6">
          <label for="firstNumber">First Number</label>
          <input type="number" class="form-control" id="firstNumber" ng-model="calc.firstNumber">
        </div>

        <div class="col-xs-6">
          <label for="secondNumber">Second Number</label>
          <input type="number" class="form-control" id="secondNumber" ng-model="calc.secondNumber">
        </div>
      </div>

        <p>Adding {{calc.firstNumber}} with {{calc.secondNumber}} results in {{calc.add()}}</p>
        <p>Subtracting {{calc.firstNumber}} with {{calc.secondNumber}} results in {{calc.subtract()}}</p>
        <p>Multiplying {{calc.firstNumber}} with {{calc.secondNumber}} results in {{calc.multiply()}}</p>
        <p>Dividing {{calc.firstNumber}} with {{calc.secondNumber}} results in {{calc.divide()}}</p>
        <p>Modulo Operation of {{calc.firstNumber}} with {{calc.secondNumber}} results in {{calc.modulo()}}</p>
    </div>
    <button ng-click="hideSecond()" class="btn btn-success">{{calc.secondButtonText}}</button>
  </div>

</div>

app/views/welcome/services_intro.html.erb
<div class="jumbotron" ng-app="workshop-2">
  <header>
    <h1>Modules, Controllers, Directives</h1>
  </header>
  <h2>A basic calculator</h2>
  <div class="main-container" ng-controller="CalculatorController">
    <div ng-hide="firstHidden">
      <div class="form-group row">
        <div class="col-xs-6">
          <label for="firstNumber">First Number</label>
          <input type="number" class="form-control" id="firstNumber" ng-model="firstNumber">
        </div>

        <div class="col-xs-6">
          <label for="secondNumber">Second Number</label>
          <input type="number" class="form-control" id="secondNumber" ng-model="secondNumber">
        </div>
      </div>
      
      <p>Adding {{firstNumber}} with {{secondNumber}} results in {{add()}}</p>
      <p>Subtracting {{firstNumber}} with {{secondNumber}} results in {{subtract()}}</p>
      <p>Multiplying {{firstNumber}} with {{secondNumber}} results in {{multiply()}}</p>
      <p>Dividing {{firstNumber}} with {{secondNumber}} results in {{divide()}}</p>
      <p>Modulo Operation of {{firstNumber}} with {{secondNumber}} results in {{modulo()}}</p>
    </div>
    <button ng-click="hideFirst()" class="btn btn-success">{{buttonText}}</button>
  </div>

  <h2>Alternate Calculator</h2>
  <div class="main-container" ng-controller="AlternateCalculateController as calc">
    <div class="form-group row">
      <div class="col-xs-6">
        <label for="firstNumber">First Number</label>
        <input type="number" class="form-control" id="firstNumber" ng-model="calc.firstNumber">
      </div>

      <div class="col-xs-6">
        <label for="secondNumber">Second Number</label>
        <input type="number" class="form-control" id="secondNumber" ng-model="calc.secondNumber">
      </div>
    </div>
      <p>Adding {{calc.firstNumber}} with {{calc.secondNumber}} results in {{calc.add()}}</p>
      <p>Subtracting {{calc.firstNumber}} with {{calc.secondNumber}} results in {{calc.subtract()}}</p>
      <p>Multiplying {{calc.firstNumber}} with {{calc.secondNumber}} results in {{calc.multiply()}}</p>
      <p>Dividing {{calc.firstNumber}} with {{calc.secondNumber}} results in {{calc.divide()}}</p>
      <p>Modulo Operation of {{calc.firstNumber}} with {{calc.secondNumber}} results in {{calc.modulo()}}</p>
  </div>  
</div>

app/views/welcome/solution_1.html.erb
<div class="jumbotron" ng-app ng-init="first_string='';second_string=''">
  <header>
    <h1>Exercise1: You will be practising two way data binding here.</h1>
  </header>
  <div class="main-container">
    <div class="row">
      <h3>Problem: Create a Form that takes two strings and concatenates those two and outputs the result</h3>
    </div>
    <div class="form-group row">
      <div class="col-xs-6">
        <label for="first_string">First string</label>
        <input type="text" class="form-control" id="first_string" ng-model="first_string">
      </div>

      <div class="col-xs-6">
        <label for="second_string">Second string</label>
        <input type="text" class="form-control" id="second_string" ng-model="second_string">
      </div>
    </div>
    <div class="row">
      <p>Concatenating {{first_string}} with {{second_string}} results in {{first_string.concat(second_string)}}</p>
    </div>
  </div>
</div>